name       : python-incremental
version    : 21.3.0
release    : 6
source     :
    - https://github.com/twisted/incremental/archive/refs/tags/incremental-21.3.0.tar.gz : 57b6a0785f265ffe59a454276efac1062943bb5b7bff7b5505bf054a563c22c4
homepage   : https://github.com/twisted/incremental
license    : MIT
component  : programming.python
summary    : A library for versioning your Python projects
description: |
    Incremental is a small library that versions your Python projects.
builddeps  :
    - python-click   # Check
    - python-pytest  # Check
    - python-twisted # Check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
