name       : python-incremental
version    : 17.5.0
release    : 1
source     :
    - https://github.com/twisted/incremental/archive/incremental-17.5.0.tar.gz : 7be9a13ebb2ad1dd1ed3ecf547c3fa6e1154bb793418c6cc504b9b6039b0045a
license    : MIT
component  : programming.python
summary    : A library for versioning your Python projects
description: |
    Incremental is a small library that versions your Python projects.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
