name       : python-incremental
version    : 17.5.0
release    : 5
source     :
    - https://github.com/twisted/incremental/archive/incremental-17.5.0.tar.gz : 7be9a13ebb2ad1dd1ed3ecf547c3fa6e1154bb793418c6cc504b9b6039b0045a
homepage   : https://github.com/twisted/incremental
license    : MIT
component  : programming.python
summary    : A library for versioning your Python projects
description: |
    Incremental is a small library that versions your Python projects.
builddeps  :
    - python-click   # Check
    - python-pytest  # Check
    - python-twisted # Check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
